import React from 'react'

export const Image = () => {
  return (
    <div>
      <h4>Gallery</h4>
      <img
        width="600"
        height="600"
        src={require('../images/image1.jpg')}
        alt="random1"
        className="skewElem"
      />
      <img
        width="600"
        height="600"
        src={require('../images/image2.jpg')}
        alt="random2"
        className="skewElem"
      />
      <img
        width="600"
        height="600"
        src={require('../images/image3.jpg')}
        alt="random3"
        className="skewElem"
      />
      <img
        width="600"
        height="600"
        src={require('../images/image4.jpg')}
        alt="random4"
        className="skewElem"
      />
      <img
        width="600"
        height="600"
        src={require('../images/image5.jpg')}
        alt="random5"
        className="skewElem"
      />
      <img
        width="600"
        height="600"
        src={require('../images/image6.jpg')}
        alt="random6"
        className="skewElem"
      />
      <img
        width="600"
        height="600"
        src={require('../images/image7.jpg')}
        alt="random7"
        className="skewElem"
      />
      <img
        width="600"
        height="600"
        src={require('../images/image8.jpg')}
        alt="random8"
        className="skewElem"
      />
      <img
        width="600"
        height="600"
        src={require('../images/image9.jpg')}
        alt="random9"
        className="skewElem"
      />
      <img
        width="600"
        height="600"
        src={require('../images/image1.jpg')}
        alt="random0"
        className="skewElem"
      />
    </div>
  );
}
