import React from 'react'

export const Image = () => {
  return (
    <div>
      <img
        width="600"
        height="600"
        src="https://picsum.photos/600/600?random=1"
        alt="random1"
        className="skewElem"
      />
      <img
        width="600"
        height="600"
        src="https://picsum.photos/600/600?random=2"
        alt="random2"
        className="skewElem"
      />
      <img
        width="600"
        height="600"
        src="https://picsum.photos/600/600?random=3"
        alt="random3"
        className="skewElem"
      />
      <img
        width="600"
        height="600"
        src="https://picsum.photos/600/600?random=4"
        alt="random4"
        className="skewElem"
      />
      <img
        width="600"
        height="600"
        src="https://picsum.photos/600/600?random=5"
        alt="random5"
        className="skewElem"
      />
      <img
        width="600"
        height="600"
        src="https://picsum.photos/600/600?random=6"
        alt="random6"
        className="skewElem"
      />
      <img
        width="600"
        height="600"
        src="https://picsum.photos/600/600?random=7"
        alt="random7"
        className="skewElem"
      />
      <img
        width="600"
        height="600"
        src="https://picsum.photos/600/600?random=8"
        alt="random8"
        className="skewElem"
      />
      <img
        width="600"
        height="600"
        src="https://picsum.photos/600/600?random=9"
        alt="random9"
        className="skewElem"
      />
      <img
        width="600"
        height="600"
        src="https://picsum.photos/600/600?random=10"
        alt="random0"
        className="skewElem"
      />
    </div>
  );
}
